### ISSUE TITLE
warning: changing start of section .bss by 24 bytes

### ISSUE THREAD

**Issue by fdarosa2663** [profezzorn/arduino-proffieboard#1]
c:/users/fernandod/appdata/local/arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 24 bytes

**Comment by gbrowerjr** [comment]
This is just using serial for usb type. The start of section changes depending on features enabled. followed by an overflow. i've added some big styles but really not that many. I have diagnostics disabled as well as a lot of the fett263 options. anything else taking up room that can be removed?

c:/users/gbrow/appdata/local/arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

**Comment by profezzorn** [comment]
This is just a warning, and it can be safely ignored.
It happens randomly when the first symbol in a section has a higher alignment requirement than what is stated in the linker.
Last I checked, I did not find a way to turn this warning off.
