### ISSUE TITLE
New to this any help is appreciated

### ISSUE THREAD

**Issue by pokemoneater** [profezzorn/arduino-proffieboard#10]
I keep trying to upload to my board and I get this error. 

Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Proffieboard V2, Serial, SDCARD (SPI), 80 MHz, Smallest Code"

c:/users/justin/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe:C:\Users\Justin\Documents\ArduinoData\packages\proffieboard\hardware\stm32l4\3.6.0\variants\STM32L433CC-ProffieboardV2/linker_scripts/STM32L433CC_FLASH.ld:224: warning: memory region `SRAM2' not declared

c:/users/justin/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: C:\Users\Justin\AppData\Local\Temp\ProffieOS.ino.elf.Iv49DP.ltrans0.ltrans.o: in function `main':

C:\Users\Justin\Documents\ArduinoData\packages\proffieboard\hardware\stm32l4\3.6.0\cores\stm32l4/main.cpp:129: undefined reference to `setup'

c:/users/justin/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: C:\Users\Justin\Documents\ArduinoData\packages\proffieboard\hardware\stm32l4\3.6.0\cores\stm32l4/main.cpp:133: undefined reference to `loop'

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board Proffieboard V2.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by profezzorn** [comment]
This usually means that you loaded up the config file in Arduino and tried to compile it.
Some people make the mistake of scoping out the contents of ProffieOS.ino and replacing it with the config file, that also gives this error.
