### ISSUE TITLE
Slow boot, font directory not found

### ISSUE THREAD

**Issue by Neallsies** [profezzorn/arduino-proffieboard#12]
I got a new saber and sometimes it will not turn on for a good 7-10 seconds and say font directory not found, SD card not found. But most of the time it works fine. I also replaced the SD card with 3 different ones to see if that would fix the issue and it is still doing it. Not sure if it's a bad board or something else.

**Comment by profezzorn** [comment]
This sounds similar to the sd card not found thread on the crucible:
https://crucible.hubbe.net/t/sd-card-not-found-mystery/1622

Unfortunately we're not sure what's causing it. It seems tied to certain software on certain boards. But we still don't have a good way to narrow it down to an actual cause.

**Comment by Neallsies** [comment]
Do you think an older version of proffie would fix it? I updated to 6.7 and thats when it started I think.

**Comment by profezzorn** [comment]
Some people have had it work better with older versions of ProffieOS, but we don't know why.
If old versions works better for you, I would be most grateful if you could try different versions of ProffieOS to figure out when the problem actually started.

**Comment by Neallsies** [comment]
Sure! I'tll probably be tomorrow or late tonight but I'll post my findings!

**Comment by Neallsies** [comment]
I went back to 5.6 and it was still doing it so I got frustrated and gave up for the day lol.

**Comment by Neallsies** [comment]
mmkay so i tried using a base os5 config and when i added the blade code at the bottom for i think the crystal chamber it messed up and started doing it again? 
BladeConfig blades[] = {
 { 0, WS281XBladePtr<130, bladePin, Color8::GRB, PowerPINS<bladePowerPin2, bladePowerPin3> >(),
    WS281XBladePtr<1, blade4Pin, Color8::GRB, PowerPINS<bladePowerPin6> >()
  , CONFIGARRAY(presets) },

**Comment by profezzorn** [comment]
How is the crystal chamber wired?
Is it connected to the 3.3v pad?

**Comment by profezzorn** [comment]
If this is still an issue, go to https://crucible.hubbe.net/ to get help.
