### ISSUE TITLE
proffie help com port issues

### ISSUE THREAD

**Issue by proffien00b93** [profezzorn/arduino-proffieboard#13]
I recently have trouble loading anything when updating the board software to the latest one which is 3.6.0
the board wont be read at all and i fresh installed everything and redid all the steps.

so i rollback the update and went to 2.2.0 instead and arduino instantly read the board and COM4 is indicated.

i update my configs and it shown this error and my PC spammed a "please insert a disk into USB Drive F:" repeatedly like the board has been connected and disconnected multiple times. below is the error message when i did the first time, the download went thru but now i wanna add more stuffs, i can't get anything done anymore.

Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Proffieboard V2, Serial + Mass Storage + WebUSB, SDCARD (SPI), 80 MHz, Smallest Code"

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

Sketch uses 165496 bytes (67%) of program storage space. Maximum is 245760 bytes.
![Screenshot 2022-11-13 151144](https://user-images.githubusercontent.com/118098028/201510340-9fbb5e51-9367-4312-97e1-0698bcebb49e.jpg)

1

Cannot open DFU device 0483:df11

Cannot open DFU device 0483:df11

2

Cannot open DFU device 0483:df11

dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.

Copyright 2010-2016 Tormod Volden and Stefan Schmidt

This program is Free Software and has ABSOLUTELY NO WARRANTY

Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Opening DFU capable USB device...

ID 0483:df11

Run-time device DFU version 011a

Claiming USB DFU Interface...

Setting Alternate Setting #0 ...

Determining device status: state = dfuERROR, status = 10

dfuERROR, clearing status

Determining device status: state = dfuIDLE, status = 0

dfuIDLE, continuing

DFU mode device DFU version 011a

Device returned transfer size 2048

DfuSe interface name: "Internal Flash  "

Downloading to address = 0x08000000, size = 165504

Download	[=========================] 100%       165504 bytes

Download done.

File downloaded successfully

Transitioning to dfuMANIFEST state

Cannot open DFU device 0483:df11

processing.app.SerialException: Error opening serial port 'COM4'.

	at processing.app.Serial.<init>(Serial.java:152)

	at processing.app.Serial.<init>(Serial.java:82)

	at processing.app.SerialMonitor$2.<init>(SerialMonitor.java:132)

	at processing.app.SerialMonitor.open(SerialMonitor.java:132)

	at processing.app.AbstractMonitor.resume(AbstractMonitor.java:132)

	at processing.app.Editor.resumeOrCloseSerialMonitor(Editor.java:2126)

	at processing.app.Editor.access$1300(Editor.java:116)

	at processing.app.Editor$UploadHandler.run(Editor.java:2095)

	at java.lang.Thread.run(Thread.java:748)

Caused by: jssc.SerialPortException: Port name - COM4; Method name - openPort(); Exception type - Port busy.

	at jssc.SerialPort.openPort(SerialPort.java:164)

	at processing.app.Serial.<init>(Serial.java:141)

	... 8 more

Error opening serial port 'COM4'.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

---------- *below is the error msg after I try to update my board again--------------------------------------------------------

Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Proffieboard V2, Serial, SDCARD (SPI), 80 MHz, Smallest Code"

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

c:/users/mzj93/documents/arduinodata/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 8 bytes

Sketch uses 166024 bytes (67%) of program storage space. Maximum is 245760 bytes.

1

2

3

4

5

6

7

8

9

10

Board at COM4 is not available

Board at COM4 is not available

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

So how should i update back to 3.6 and figure things out again why my board isnt being detected by software but my pc does?

**Comment by profezzorn** [comment]
Did you run zadig as specified here:
https://github.com/profezzorn/ProffieOS/wiki/zadig

**Comment by proffien00b93** [comment]
> Did you run zadig as specified here: https://github.com/profezzorn/ProffieOS/wiki/zadig ?

Hi yes i did. reinstalled a few times.

**Comment by profezzorn** [comment]
Do you have an SD-card in the board?

If all else fails, you'll need to do BOOT+RESET to put the board in bootloader mode, then press upload in arduino.
