### ISSUE TITLE
Proffieboard not installing

### ISSUE THREAD

**Issue by Cutiepie751** [profezzorn/arduino-proffieboard#15]
I try to install the proffieboard on arduino and I keep getting CRC doesn't match, file is corrupted. please help

**Comment by profezzorn** [comment]
I suspect it's because of this:
https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/
The problem should resolve itself once they revert the change.
If it's still a problem tomorrow, please re-open this issue.

**Comment by Cutiepie751** [comment]
What does this mean? I clicked on the link but still don't understand what
it means

**Comment by profezzorn** [comment]
It means try again.
If it doesn't work, try again tomorrow.
If it *still* doesn't work, we'll have to investigate further.
