### ISSUE TITLE
Uploading Soundfonts to Saber but i keep getting this error? 'C:\Users\Cole' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Tipicole** [profezzorn/arduino-proffieboard#16]
c:/users/cole healey/appdata/local/arduino15/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe:C:\Users\Cole Healey\AppData\Local\Arduino15\packages\proffieboard\hardware\stm32l4\3.6\variants\STM32L433CC-ProffieboardV2/linker_scripts/STM32L433CC_FLASH.ld:224: warning: memory region `SRAM2' not declared
c:/users/cole healey/appdata/local/arduino15/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 16 bytes
c:/users/cole healey/appdata/local/arduino15/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 16 bytes
c:/users/cole healey/appdata/local/arduino15/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 16 bytes
c:/users/cole healey/appdata/local/arduino15/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 16 bytes
c:/users/cole healey/appdata/local/arduino15/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: changing start of section .bss by 16 bytes
Sketch uses 214104 bytes (81%) of program storage space. Maximum is 262144 bytes.
'C:\Users\Cole' is not recognized as an internal or external command,
operable program or batch file.
Failed uploading: uploading error: exit status 1

**Comment by profezzorn** [comment]
Arduino 2.x has issues with spaces in filenames.
Either use Arduino 1.19.x, or make sure that there are no spaces in the "arduino15" directory.

**Comment by profezzorn** [comment]
not 1.19.x
I meant 1.8.19, which I think was the last version before 2.x

**Comment by Tipicole** [comment]
> not 1.19.x I meant 1.8.19, which I think was the last version before 2.x

that's seems to fix the issue. thanks!
