### ISSUE TITLE
Board Manager Proffie 2.2.0 Error

### ISSUE THREAD

**Issue by crizouch** [profezzorn/arduino-proffieboard#7]
Hello, I'm trying to install Proffieboard version 2.2.0 but it gives me this error: Error downloading https://fredrik.hubbe.net/lightsaber/gcc/gcc-arm-none-eabi-9-2020-q2-update-win32.zip

I was able to download version 1.0.0.

**Comment by profezzorn** [comment]
If you click on that link, can you download it?
What version of arduino are you using?

**Comment by crizouch** [comment]
When I click on the link, it says "This site can’t be reached". I'm using arduino 1.8.16 which I downloaded this evening.

**Comment by crizouch** [comment]
This might be related, I get the same "This site can't be reached" error when I try these sites:
https://fredrik.hubbe.net/lightsaber/ProffieOS-v5.9.zip
https://fredrik.hubbe.net/lightsaber/v5/

**Comment by profezzorn** [comment]
Must be some internet outage somewhere, I can reach it just fine.

**Comment by crizouch** [comment]
Okay. Thank you. I will try again later.

**Comment by profezzorn** [comment]
Closing as old.
