### ISSUE TITLE
Files Not Sending to Saber

### ISSUE THREAD

**Issue by GarfieldLasagna42** [profezzorn/arduino-proffieboard#8]
I've been trying to upload my new config files to my proffieboard v.2 and I have 2 issues. First off, when I use Zadig on my computer, the "WCID" box has a red "X" in it, and secondly, when I use arduino, it says my board is not connected even though I have all of the port and serial options selected correctly. Could the red "X" in zadig be the root of this problem? Any help is appreciated.

**Comment by profezzorn** [comment]
This is old, and hopefully solved.
If not, please go to https://crucible.hubbe.net/ to get help.
