### ISSUE TITLE
I am new to this

### ISSUE THREAD

**Issue by alexw0514** [profezzorn/arduino-proffieboard#9]
I am new to the proffie stuff here and i was installing 3.6.0 on ardunio following landosabers' youtube video when I canceled the installation on accident and then I went to restart it but it won't let me be are a "file with that name already exists" and since I have no clue how to work this idc how to delete it.

**Comment by profezzorn** [comment]
Can you cut-n-paste the full error message so I can see what file it's talking about?
Does restarting arduino and/or rebooting your computer help?
